# Valine
# For more information: https://valine.js.org, https://github.com/xCss/Valine
valine:
  enable: false
  appId: # Your leancloud application appid
  appKey: # Your leancloud application appkey
  serverURLs: # When the custom domain name is enabled, fill it in here
  placeholder: "填写邮箱可以及时收到回复哦(●'◡'●)" # Comment box placeholder
  avatar: 'wavatar' # Gravatar style
  meta: [nick, mail, link] # Custom comment header
  pageSize: 10 # Pagination size
  lang: # Language, available values: en, zh-cn
  # Warning: Do not enable both `valine.visitor` and `leancloud_visitors`.
  visitor: false # Article reading statistic
  comment_count: true # If false, comment count will only be displayed in post page, not in home page
  recordIP: false # Whether to record the commenter IP
  enableQQ: false # Whether to enable the Nickname box to automatically get QQ Nickname and QQ Avatar
  requiredFields: [] # Set required fields: [nick] | [nick, mail]
  master: ''    #博主邮箱md5
  tagMeta: ["博主","小伙伴","访客"]     #标识字段名
  friends:  [""]                        #小伙伴邮箱Md5
  metaPlaceholder: {"nick":"昵称/QQ号","mail":"邮箱（完全保密）"}